//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Admin
    {
        [Display(Name = "Tài Khoản:")]
        public string TaiKhoan { get; set; }

        public string Password { get; set; }

        public string Email { get; set; }

        [Display(Name = "Số Điện Thoại:")]
        public string SDT { get; set; }
    }
}
