//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class CamNangDuLich
    {
        public int ID_CNDL { get; set; }
        public string TenCNDL { get; set; }
        public string ImageCNDL { get; set; }
        public string NoiDungCNDL { get; set; }
        public Nullable<System.DateTime> NgayNhapCN { get; set; }
        [NotMapped]
        public HttpPostedFileBase ImageUpload { get; set; }
    }
}
