//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDatVe
    {
        public int ID_CT { get; set; }
        public Nullable<int> ID_Tour { get; set; }
        public Nullable<int> ID_DatVe { get; set; }
        public Nullable<int> SoLuongVe { get; set; }
        public Nullable<double> ThanhTien { get; set; }
    
        public virtual DatVe DatVe { get; set; }
        public virtual Tour Tour { get; set; }
    }
}
