//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ChiTietDatVe
    {
        [Display(Name = "Mã Chi Tiết Đặt Vé:")]
        public int ID_CT { get; set; }

        [Display(Name = "Mã Tour:")]
        public Nullable<int> ID_Tour { get; set; }

        [Display(Name = "Mã Đặt Vé:")]
        public Nullable<int> ID_DatVe { get; set; }

        [Display(Name = "Số Lượng Vé:")]
        public Nullable<int> SoLuongVe { get; set; }

        [Display(Name = "Thành Tiền:")]
        public Nullable<double> ThanhTien { get; set; }
    
        public virtual DatVe DatVe { get; set; }
        public virtual Tour Tour { get; set; }
    }
}
