//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class KhachHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachHang()
        {
            this.DatVes = new HashSet<DatVe>();
        }
        [Required(ErrorMessage = "Nhập Mã hiển thị.")]
        [Display(Name = "Mã hiển thị:")]
        public int ID_KH { get; set; }

        [Required(ErrorMessage = "Nhập Họ tên.")]
        [Display(Name = "Họ tên:")]
        public string HoTenKH { get; set; }

        [Required(ErrorMessage = "Nhập Số điện thoại.")]
        [Display(Name = "Số điện thoại:")]
        public string SDT { get; set; }

        [Required(ErrorMessage = "Nhập Email.")]
        [Display(Name = "Email:")]
        public string Email { get; set; }

        [Display(Name = "Ngày sinh:")]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:MM/dd/yyyy}")]
        public Nullable<System.DateTime> NgaySinh { get; set; }

        [Required(ErrorMessage = "Nhập Giới tính.")]
        [Display(Name = "Giới tính:")]
        public string GioiTinh { get; set; }

        [Required(ErrorMessage = "Nhập Địa chỉ.")]
        [Display(Name = "Địa chỉ:")]
        public string DiaChi { get; set; }

        [Required(ErrorMessage = "Nhập Password.")]
        [Display(Name = "Password:")]
        [DataType(DataType.Password)]
        public string Password { get; set; }


        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatVe> DatVes { get; set; }
    }
}
