//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichTrinh
    {
        public int ID_LichTrinh { get; set; }
        public Nullable<int> ID_Tour { get; set; }
        public string Ngay { get; set; }
        public string TenLT { get; set; }
        public string HinhAnhLT { get; set; }
        public string Mota { get; set; }
    
        public virtual Tour Tour { get; set; }
    }
}
