//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhaiHoi
    {
        public int ID_PH { get; set; }
        public Nullable<int> ID_Tour { get; set; }
        public string TenNguoiGui { get; set; }
        public string Email { get; set; }
        public string TieudePH { get; set; }
        public string NoidungPH { get; set; }
        public Nullable<System.DateTime> NgayGui { get; set; }
    
        public virtual Tour Tour { get; set; }
    }
}
