//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class TinTuc
    {
        [Display(Name = "Mã Tin Tức:")]
        public int ID_TT { get; set; }

        [Display(Name = "Tên Tin Tức:")]
        public string TenTT { get; set; }

        [Display(Name = "Hình Ảnh:")]
        public string ImageTT { get; set; }

        [Display(Name = "Nội Dung:")]
        public string NoiDungTT { get; set; }
        public Nullable<System.DateTime> NgayNhapTT { get; set; }
        [NotMapped]
        public HttpPostedFileBase ImageUpload { get; set; }

    }
}
