//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Tour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tour()
        {
            this.ChiTietDatVes = new HashSet<ChiTietDatVe>();
            this.LichTrinhs = new HashSet<LichTrinh>();
            this.PhaiHois = new HashSet<PhaiHoi>();
        }

        [Display(Name = "Mã Tour:")]
        public int ID_Tour { get; set; }

        [Display(Name = "Tên Tour:")]
        public string TenTour { get; set; }

        [Display(Name = "Hình Ảnh:")]
        public string HinhAnh { get; set; }

        [Display(Name = "Lịch Trình:")]
        public string MoTa { get; set; }

        [Display(Name = "Khách Sạn:")]
        public string KhachSan { get; set; }

        [Display(Name = "Phương Tiện:")]
        public string PhuongTien { get; set; }

        [Display(Name = "Gía Tour:")]
        public Nullable<decimal> Gia { get; set; }

        [Display(Name = "Ngày Khởi Hành:")]
        public Nullable<System.DateTime> NgayKhoiHanh { get; set; }

        [Display(Name = "Thời Gian:")]
        public string ThoiGian { get; set; }

        [Display(Name = "Địa Chỉ Tập Trung:")]
        public string DiaChiTapTrung { get; set; }

        [Display(Name = "Mã Loại Tour:")]
        public Nullable<int> ID_LoaiTour { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDatVe> ChiTietDatVes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichTrinh> LichTrinhs { get; set; }
        public virtual LoaiTour LoaiTour { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhaiHoi> PhaiHois { get; set; }

        [NotMapped]
        public HttpPostedFileBase ImageUpload { get; set; }

    }
}
