//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoAn.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Web;

    public partial class Tour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tour()
        {
            HinhAnh = "~/Images/add-image.png";
            this.chitietDHs = new HashSet<chitietDH>();
            this.LichTrinhs = new HashSet<LichTrinh>();
            this.PhaiHois = new HashSet<PhaiHoi>();
        }
    
        public int ID_Tour { get; set; }

        [Display(Name = "Tên Tour")]
        [Required(ErrorMessage = "Vui lòng nhập tên Tour")]
        public string TenTour { get; set; }

        [Display(Name = "Hình Ảnh")]
        [Required(ErrorMessage = "Vui lòng thêm hình ảnh")]
        public string HinhAnh { get; set; }

        [Display(Name ="Mô Tả")]
        [Required(ErrorMessage = "Vui lòng nhập mô tả")]
        public string MoTa { get; set; }

        [Display(Name = "Khách Sạn")]
        [Required(ErrorMessage = "Vui lòng nhập khách sạn")]
        public string KhachSan { get; set; }

        [Display(Name = "Phương Tiện")]
        [Required(ErrorMessage = "Vui lòng nhập phương tiện")]
        public string PhuongTien { get; set; }

        [Display(Name = "Chi Phí")]
        [Required(ErrorMessage = "Vui lòng nhập chi phí")]
        public Nullable<decimal> Gia { get; set; }

        [Display(Name = "Ngày khởi hành")]
        [Required(ErrorMessage = "Vui lòng chọn ngày khởi hành")]
        public Nullable<System.DateTime> NgayKhoiHanh { get; set; }

        [Display(Name = "Ngày kết thúc")]
        [Required(ErrorMessage = "Vui lòng chọn ngày kết thúc")]
        public Nullable<System.DateTime> NgayKetThuc { get; set; }

        [Display(Name = "Ngày tập trung")]
        [Required(ErrorMessage = "Vui lòng chọn ngày tập trung")]
        public Nullable<System.DateTime> NgayTapTrung { get; set; }

        [Display(Name = "Địa chỉ tập trung")]
        [Required(ErrorMessage = "Vui lòng nhập địa điểm tập trung")]
        public string DiaChiTapTrung { get; set; }

        [Display(Name = "Loại Tour")]
        public Nullable<int> ID_LoaiTour { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chitietDH> chitietDHs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LichTrinh> LichTrinhs { get; set; }
        public virtual LoaiTour LoaiTour { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhaiHoi> PhaiHois { get; set; }


        [NotMapped]
        public HttpPostedFileBase ImageUpload { get; set; }
    }
}
